# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flynt-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_25f1a00c7f314f5d9587ffed18280bca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6fcad1728f67449181f5163d274a3834 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_25f1a00c7f314f5d9587ffed18280bca }}/valmalio/docker-example-voting-app:${{ github.sha }}
        file: ./vote/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flynt-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bd525694804f413688d9c42fad8f63e6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_25f1a00c7f314f5d9587ffed18280bca }}/valmalio/docker-example-voting-app:${{ github.sha }}'
